server:
    port: 8090
    session:
        timeout: 1800

endpoints:
    enabled: false
    shutdown:
        enabled: false
    jmx:
        enabled: false

spring:
    profiles:
        active: dev
    datasource:
        master:
            dataSourceClassName: org.gjt.mm.mysql.Driver
            #url: jdbc:mysql://172.31.11.200:3306/wicrowd_db?useUnicode=true&characterEncoding=utf-8
            #databaseName: wicrowd_db
            url: jdbc:mysql://192.168.123.52:3306/ka_intra?characterSetResults=utf8&characterEncoding=utf8&useUnicode=true
            databaseName: ka_intra
            serverName: kasset
            username: root
            password: K$asseti44
            #password: wicrowd2016!@#$
            validationQuery: SELECT 1
            testOnBorrow: true
        slave:
            dataSourceClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#            dataSourceClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            url: jdbc:sqlserver://192.168.120.50:3433;DatabaseName=dzicube;characterEncoding=utf8;useUnicode=true
            databaseName: dzicube
            #url: jdbc:mysql://192.168.123.52:3306/ka_intra?characterSetResults=utf8&characterEncoding=utf8&useUnicode=true
            #databaseName: ka_intra
            serverName: dzicube
            username: dzicube
            #password: K$asseti44
            password: ejwhs123$
            validationQuery: SELECT 1
            testOnBorrow: true
    jpa:
        showSql: true
        properties:
            hibernate:
                format_sql: true

    redis:
        host: 127.0.0.1
        port: 6379

    messages:
         basename: messages/messages

    social:
        twitter:
            consumerKey: lor0w57qTyYaiv7OCkffqOwZV
            consumerSecret: YO3guSJaRFJkpd2J8EPqSpv78I6g8fyMq3X8I3qs2uWSbbJrBI
        facebook:
            appId: '1865799810313126'
            appSecret: 522f20a5760565c1461847eeb20772df

    mail:
        host: 119.206.195.229
        username: wicrowd@kasset.co.kr
        password: asdf6256
        port: 25

xcrowdfund:
   restUrl: http://127.0.0.1:8070

pdf:
    projectDocument: /Users/bridge/Documents/develop/intellij-workspace/wicrowd-java/testdata
    cssfile: /Users/bridge/Documents/develop/intellij-workspace/wicrowd-java/test.css
    fontFile: /Users/bridge/Documents/develop/intellij-workspace/wicrowd-java/testdata/font/MALGUN.TTF
    zipmakerUrl: http://52.79.135.24:8080/add

multipart:
    maxFileSize: 10Mb
    maxRequestSize: 30Mb

develop: true

upload:
    fileLocation: /

logging:
    config: classpath:logback.xml

aeskey: M3OuXbwA3AcJq9oa-c_YRONCiYk8SiEd9KsRFaj1oTM

sms:
  from: '025506256'


social:
  facebook:
      fbAppId: '1865799810313126'

admin:
  email: webmaster@kasset.co.kr

subscribe:
    has_encrypt: N
    hd_ep_type: CERT

